baseURL = "http://albizures.com/"
languageCode = "en-us"
title = "Jose Albizures"
pygmentsStyle = "monokai"
pygmentsCodefences = true
pygmentsOptions = "linenos=true,lineanchors=true,full=true"
pygmentsUseClasses = true
theme = "black-and-light"